@startuml
enum TokenType {
    Plus,
    Minus,
    Asterisk,
    Slash,
    LeftBrace,
    RightBrace,
    LeftParenthesis,
    RightParenthesis,
    Semicolon,
    Dot,
    Comma,
    Exclamation,
    Equal,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    ExclamationEqual,
    EqualEqual,
    Identifier,
    String,
    Integer,
    Float,
    True,
    False,
    Import,
    Func,
    Var,
    If,
    While,
    Return,
    Print,
}
@enduml
