@startuml
!include .\\Cricket\Program.puml
!include .\\CricketBootstrap\CricketBootstrap.puml
!include .\\CricketTest\ParserTest.puml
!include .\\CricketTest\ScannerTest.puml
!include .\\Cricket\Interpreter\DataType.puml
!include .\\Cricket\Interpreter\Interpreter.puml
!include .\\CricketBootstrap\Environment\EnvironmentManager.puml
!include .\\CricketBootstrap\Lib\CastStringToFloat.puml
!include .\\CricketBootstrap\Lib\CastStringToInteger.puml
!include .\\CricketBootstrap\Lib\HttpRequestValue.puml
!include .\\CricketBootstrap\Server\DynamicDocument.puml
!include .\\CricketBootstrap\Server\HttpServer.puml
!include .\\Cricket\Interpreter\Environment\Environment.puml
!include .\\Cricket\Interpreter\Environment\VariableWrapper.puml
!include .\\Cricket\Interpreter\Error\DisallowedSyntaxError.puml
!include .\\Cricket\Interpreter\Error\InvalidReturnStatementError.puml
!include .\\Cricket\Interpreter\Error\MissingReturnStatementError.puml
!include .\\Cricket\Interpreter\Error\ResolverError.puml
!include .\\Cricket\Interpreter\Error\UnexpectedEndOfFileError.puml
!include .\\Cricket\Interpreter\Error\UnexpectedSyntaxError.puml
!include .\\Cricket\Interpreter\Error\UnrecognizedSyntaxError.puml
!include .\\Cricket\Interpreter\Parser\Parser.puml
!include .\\Cricket\Interpreter\Parser\Resolver.puml
!include .\\Cricket\Interpreter\Scanner\Scanner.puml
!include .\\Cricket\Interpreter\Scanner\Token.puml
!include .\\Cricket\Interpreter\Scanner\TokenType.puml
!include .\\Cricket\Interpreter\Parser\Statement\AssignmentStatement.puml
!include .\\Cricket\Interpreter\Parser\Statement\FunctionStatement.puml
!include .\\Cricket\Interpreter\Parser\Statement\IfStatement.puml
!include .\\Cricket\Interpreter\Parser\Statement\IStatement.puml
!include .\\Cricket\Interpreter\Parser\Statement\PrintStatement.puml
!include .\\Cricket\Interpreter\Parser\Statement\ReturnStatement.puml
!include .\\Cricket\Interpreter\Parser\Statement\VariableStatement.puml
!include .\\Cricket\Interpreter\Parser\Statement\WhileStatement.puml
!include .\\Cricket\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\Cricket\obj\Debug\net6.0\Cricket.AssemblyInfo.puml
!include .\\Cricket\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Cricket\obj\Debug\netcoreapp3.1\Cricket.AssemblyInfo.puml
!include .\\CricketBootstrap\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CricketBootstrap\obj\Debug\net6.0\CricketBootstrap.AssemblyInfo.puml
!include .\\CricketBootstrap\obj\Debug\net6.0\CricketBootstrap.GlobalUsings.g.puml
!include .\\CricketTest\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CricketTest\obj\Debug\net6.0\CricketTest.AssemblyInfo.puml
!include .\\Cricket\Interpreter\Parser\Statement\Expression\BinaryExpression.puml
!include .\\Cricket\Interpreter\Parser\Statement\Expression\CallExpression.puml
!include .\\Cricket\Interpreter\Parser\Statement\Expression\IExpression.puml
!include .\\Cricket\Interpreter\Parser\Statement\Expression\NegationExpression.puml
!include .\\Cricket\Interpreter\Parser\Statement\Expression\ValueExpression.puml
!include .\\Cricket\Interpreter\Parser\Statement\Expression\VariableExpression.puml
@enduml
